export const suggestions = [
  "Bagaimana cara mengatasi sakit kepala?",
  "Apa penyebab pusing saat bangun tidur?",
  "Kapan sebaiknya minum obat sakit kepala?",
  "Apakah stres bisa menyebabkan sakit kepala?",
  "Apa saja gejala migrain yang umum?",
  "Perhitungan dosis paracetamol",
  "Monitoring efek samping metformin",
  "Mekanisme kerja antihipertensi",
  "Cara kerja obat antidepresan",
  "Interaksi obat yang perlu diperhatikan",
  "Efek samping obat yang umum",
  "Rumus molaritas",
  "Konsep dasar farmakokinetik",
  "Pengertian dan tujuan terapi obat",
  "Prinsip dasar penggunaan antibiotik",
  "Farmakologi dasar",
  "Etika dalam penggunaan obat",
  "Peran farmasis dalam terapi obat",
  "Kepatuhan pasien terhadap terapi",
  "Manajemen efek samping obat",
  "Peran teknologi informasi dalam terapi obat",
  "Pendekatan berbasis bukti dalam penggunaan obat",
  "Cara menyimpan obat yang benar sesuai bentuk sediaan",
  "Apa itu obat generik bermerek?",
  "Perbedaan bioekivalensi dan bioavailabilitas",
  "Mekanisme kerja obat analgesik non-opioid",
  "Obat golongan beta blocker dan indikasinya",
  "Farmakokinetik obat rute oral vs intravena",
  "Penyebab terjadinya resistensi antibiotik",
  "Perbedaan antibiotik bakteriostatik dan bakterisidal",
  "Apa itu terapi obat individualisasi dosis?",
  "Kontraindikasi penggunaan NSAID",
  "Farmakodinamik obat antihistamin",
  "Perbedaan obat OTC dan obat ethical",
  "Kapan perlu dilakukan monitoring kadar obat dalam darah?",
  "Apa itu therapeutic drug monitoring (TDM)?",
  "Interaksi obat dengan makanan yang sering terjadi",
  "Mekanisme kerja obat proton pump inhibitor",
  "Efek samping jangka panjang kortikosteroid",
  "Apa itu obat dengan indeks terapeutik sempit?",
  "Cara membaca leaflet obat",
  "Perbedaan sediaan obat lepas cepat dan lepas lambat",
  "Mengapa ada obat yang tidak boleh dihentikan mendadak?",
  "Farmakovigilans dan pelaporan efek samping obat",
  "Prinsip farmasi klinis dalam terapi pasien",
  "Obat yang sering menyebabkan hepatotoksisitas",
  "Farmakologi sistem saraf otonom",
  "Peran farmasis dalam penyesuaian dosis gagal ginjal",
  "Farmakoterapi penyakit kronis seperti hipertensi dan diabetes",
  "Apa itu obat prodrug dan contohnya?",
  "Mengapa beberapa obat perlu uji darah rutin?",
  "Konsep dasar interaksi farmakodinamik vs farmakokinetik",
  "Obat-obat dengan risiko tinggi (high alert medication)",
  "Penggunaan antikoagulan dan monitoring INR",
  "Mekanisme kerja obat kemoterapi",
  "Prinsip penggunaan obat pada ibu hamil",
  "Kategori keamanan obat menurut FDA (A, B, C, D, X)",
  "Syarat stabilitas obat dalam penyimpanan",
  "Perbedaan sediaan tablet salut enterik dan salut gula",
  "Apa itu obat biologis dan biosimilar?",
  "Obat golongan statin dan efek sampingnya",
  "Farmakologi obat anestesi umum",
  "Perbedaan farmasi komunitas dan farmasi klinis",
  "Obat yang memerlukan resep ketat (narkotika, psikotropika)",
  "Mengapa ada obat yang harus disimpan di kulkas?",
  "Prinsip terapi kombinasi obat antihipertensi",
  "Farmakologi obat antidiabetik oral",
  "Peran farmasis dalam penelitian uji klinis obat",
];
